export const categories = [
  "Art & Design",
  "Auto & Moto",
  "Betting",
  "Blogs",
  "Books & Magazine",
  "Business & Startups",
  "Celebrities",
  "Communication",
  "Cryptocurrencies",
  "Economics & Finance",
  "Education",
  "Entertainment",
  "Fashion & Beauty",
  "Food",
  "Health",
  "Love",
  "Marketing",
  "Music",
  "News & Media",
  "Science",
  "Self Development",
  "Sports & Fitness",
  "Technology",
  "Travel",
];
